package com.eyeball.pastebin.api;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.net.URLConnection;

import com.eyeball.utils.URLPost;

public class PastebinUser {

	public static final String LOGINURL = "http://pastebin.com/api/api_login.php";

	private final String userKey;

	/**
	 * 
	 * A pastebin user
	 * 
	 * @param key
	 *            The developer key
	 * @param username
	 *            The username
	 * @param password
	 *            The password
	 * @throws IOException
	 *             If the connection to pastebin.com could not be made
	 * @throws PastebinBadAPIRequestException
	 *             If the username, password or key is incorrect
	 */
	public PastebinUser(PastebinDeveloperKey key, String username,
			String password) throws IOException, PastebinBadAPIRequestException {
		URL post = new URL(LOGINURL);
		URLConnection connection = post.openConnection();
		connection.setDoOutput(true);
		connection.setDoInput(true);
		URLPost postContents = new URLPost();
		postContents.put("api_dev_key", key.getKey());
		postContents.put("api_user_name", username);
		postContents.put("api_user_password", password);
		{
			OutputStreamWriter writer = new OutputStreamWriter(
					connection.getOutputStream());

			writer.write(postContents.getPost());
			writer.flush();
			writer.close();
		}
		StringBuilder text = new StringBuilder();
		{
			BufferedReader reader = new BufferedReader(new InputStreamReader(
					connection.getInputStream()));
			for (String line = reader.readLine(); line != null; line = reader
					.readLine()) {
				if (text.length() > 0) {
					text.append('\n');
				}
				text.append(line);
			}
			reader.close();
		}

		String result = text.toString();
		if (result.startsWith("Bad")) {
			throw new PastebinBadAPIRequestException(result);
		}
		userKey = result;
	}

	/**
	 * 
	 * Get the key generated by Pastebin
	 * 
	 * @return
	 */
	public String getUserKey() {
		return userKey;
	}

}
